# Generated by Django 5.1.5 on 2026-05-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0002_company_name_alter_calculation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='application_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='none', max_length=10),
        ),
    ]
